name: Build and Push Docker Image

on:
  push:
    branches:
      - teste_ci_cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: admiro
        password: SUZANA100

    - name: Build Docker image
      run: docker build -t admiro/todoapp:latest .

    - name: Push Docker image
      run: docker push admiro/todoapp:latest
